/** ModelArk / BytePlus server adapter: SSE chat streaming + Seedream + Seedance. */
export const MODELARK_DEFAULT_BASE_URL="https://ark.ap-southeast.bytepluses.com/api/v3";
export const SEEDREAM_50_PRO_MODEL="dola-seedream-5-0-pro-260628";
export const SEEDREAM_50_LITE_MODEL="seedream-5-0-lite-260128";
export const SEEDREAM_45_MODEL="seedream-4-5-251128";
export const SEEDANCE_25_MODEL="dreamina-seedance-2-5-260628";
export const SEEDANCE_25_DURATIONS=[4,5,6,8,10,12,15,20,25,30] as const;
export const SEEDANCE_25_RESOLUTIONS=["480p","720p"] as const;
export type ModelArkMessage={role:"system"|"user"|"assistant";content:unknown};
function cleanKey(value:string){return value.trim().replace(/^Bearer\s+/i,"").replace(/^['\"]|['\"]$/g,"")}
function apiKeys(){return [process.env.MODELARK_API_KEY,process.env.ARK_API_KEY,process.env.BYTEPLUS_API_KEY].filter((v):v is string=>Boolean(v&&v.trim())).map(cleanKey).filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i)}
export function modelArkConfig(){return{apiKey:apiKeys()[0]||"",baseUrl:(process.env.ARK_BASE_URL||process.env.BYTEPLUS_BASE_URL||MODELARK_DEFAULT_BASE_URL).replace(/\/+$/,"") ,textModel:process.env.MODELARK_TEXT_MODEL||"doubao-seed-2-0-pro",imageModel:process.env.MODELARK_IMAGE_MODEL||SEEDREAM_50_PRO_MODEL,videoModel:process.env.MODELARK_VIDEO_MODEL||SEEDANCE_25_MODEL};}
export function hasModelArkKey(){return apiKeys().length>0}
function auth(key:string){return{Authorization:`Bearer ${key}`,"Content-Type":"application/json"}}
async function modelArkFetch(url:string,init:RequestInit={}){const keys=apiKeys();if(!keys.length)throw new Error("ModelArk is not configured: set MODELARK_API_KEY or ARK_API_KEY");for(const key of keys){const headers=new Headers(init.headers);for(const [name,value] of Object.entries(auth(key)))headers.set(name,value);const r=await fetch(url,{...init,headers});if(r.status!==401)return r}throw new Error(`ModelArk authentication failed (401). The configured API key is invalid, expired, revoked, or belongs to a different ModelArk/BytePlus region. Create a current ModelArk API key and set MODELARK_API_KEY or ARK_API_KEY on the server.`)}
function normalizeImageModel(model?:string){const m=(model||"").trim().toLowerCase();if(!m)return modelArkConfig().imageModel;if(["seedream 5.0 pro","seedream 5.0 pro.","seedream-5.0-pro","seedream-5-0-pro","dola-seedream-5-0-pro"].includes(m))return SEEDREAM_50_PRO_MODEL;if(["seedream 5.0 lite","seedream-5.0-lite","seedream-5-0-lite"].includes(m))return SEEDREAM_50_LITE_MODEL;if(["seedream 4.5","seedream-4-5"].includes(m))return SEEDREAM_45_MODEL;return model}
function normalizeVideoModel(model?:string){const m=(model||"").trim().toLowerCase();if(!m)return modelArkConfig().videoModel;if(["seedance 2.5","seedance-2.5","seedance 2.5 pro","dreamina-seedance-2-5"].includes(m))return SEEDANCE_25_MODEL;return model}
export async function* streamModelArkChat(a:{messages:ModelArkMessage[];model?:string;temperature?:number;maxTokens?:number;signal?:AbortSignal}):AsyncGenerator<string>{const c=modelArkConfig();const r=await modelArkFetch(`${c.baseUrl}/chat/completions`,{method:"POST",signal:a.signal,body:JSON.stringify({model:a.model||c.textModel,messages:a.messages,stream:true,stream_options:{include_usage:true},temperature:a.temperature??.7,max_tokens:a.maxTokens??4096})});if(!r.ok||!r.body)throw new Error(`ModelArk chat ${r.status}: ${(await r.text()).slice(0,500)}`);const q=r.body.getReader(),d=new TextDecoder();let b="";try{while(true){const v=await q.read();if(v.done)break;b+=d.decode(v.value,{stream:true});const ls=b.split(/\r?\n/);b=ls.pop()||"";for(const l of ls){const s=l.trim();if(!s.startsWith("data:"))continue;const z=s.slice(5).trim();if(z==="[DONE]")return;try{const j=JSON.parse(z) as any;const x=j.choices?.[0]?.delta?.content;if(typeof x==="string"&&x)yield x}catch{}}}}finally{q.releaseLock()}}
export async function generateModelArkImage(a:{prompt:string;model?:string;imageUrls?:string[];size?:string}):Promise<string>{const c=modelArkConfig();const model=normalizeImageModel(a.model||c.imageModel);const b:any={model,prompt:a.prompt,response_format:"url",size:a.size||"2K",output_format:"png",watermark:false};if(a.imageUrls?.length)b.image=a.imageUrls.length===1?a.imageUrls[0]:a.imageUrls;const r=await modelArkFetch(`${c.baseUrl}/images/generations`,{method:"POST",body:JSON.stringify(b)});if(!r.ok)throw new Error(`ModelArk image ${r.status}: ${(await r.text()).slice(0,500)}`);const j=await r.json() as any;const u=j.data?.[0]?.url;if(!u)throw new Error("ModelArk image returned no output URL");return u}
export async function generateModelArkVideo(a:{prompt:string;model?:string;imageUrl?:string;duration?:number;resolution?:"480p"|"720p"|"1080p"|"2160p";aspectRatio?:string;timeoutMs?:number}):Promise<string>{const c=modelArkConfig();const model=normalizeVideoModel(a.model||c.videoModel);const is25=model===SEEDANCE_25_MODEL;const duration=a.duration?Math.max(is25?4:3,Math.min(is25?30:15,Math.round(a.duration))):undefined;const resolution=is25&&a.resolution&&!(SEEDANCE_25_RESOLUTIONS as readonly string[]).includes(a.resolution)?"720p":a.resolution;const content:any[]=[{type:"text",text:a.prompt.trim()}];if(a.imageUrl)content.push({type:"image_url",image_url:{url:a.imageUrl},role:"first_frame"});const body:any={model,content,watermark:false};if(duration)body.duration=duration;if(resolution)body.resolution=resolution;if(a.aspectRatio)body.ratio=a.aspectRatio;body.generate_audio=true;const cr=await modelArkFetch(`${c.baseUrl}/contents/generations/tasks`,{method:"POST",body:JSON.stringify(body)});if(!cr.ok)throw new Error(`ModelArk video create ${cr.status}: ${(await cr.text()).slice(0,500)}`);const cj=await cr.json() as any;if(!cj.id)throw new Error("ModelArk video create returned no task id");const end=Date.now()+(a.timeoutMs??900000);while(Date.now()<end){await new Promise(r=>setTimeout(r,2000));const p=await modelArkFetch(`${c.baseUrl}/contents/generations/tasks/${encodeURIComponent(cj.id)}`,{headers:{}});if(!p.ok){if(p.status===429||p.status>=500)continue;throw new Error(`ModelArk video poll ${p.status}: ${(await p.text()).slice(0,500)}`)}const j=await p.json() as any;if(j.status==="succeeded"){if(!j.content?.video_url)throw new Error("ModelArk video succeeded without video_url");return j.content.video_url}if(["failed","cancelled","expired"].includes(j.status))throw new Error(`ModelArk video ${j.status}: ${typeof j.error==="string"?j.error:j.error?.message||"unknown error"}`)}throw new Error("ModelArk video timed out")}
